#!/usr/bin/env bash
# This transfers a file from a client to a server

# Check if the number of parameters is less than 4
if [ $# -lt 4 ]; then
  # Display the usage message
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  # Exit with status code 1
  exit 1
fi

# Assign the parameters to variables
PATH_TO_FILE=$1
IP=$2
USERNAME=$3
PATH_TO_SSH_KEY=$4

# Use scp command with -i option to specify the SSH key and -o option to disable strict host key checking
scp -i "$PATH_TO_SSH_KEY" -o StrictHostKeyChecking=no "$PATH_TO_FILE" "$USERNAME@$IP:~/"
