#!/usr/bin/env bash
# Install Nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Start Nginx Service
sudo service nginx start

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

# Modify the Nginx configuration to use the custom 404 page
echo "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /usr/share/nginx/html;
  index index.html;
  server_name _;

  location / {
    try_files \$uri \$uri/ =404;
  }
  error_page 404 /custom_404.html;
  location = /custom_404.html {
    internal;
  }

  location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
  }
}" | sudo tee /etc/nginx/sites-available/default

# Restart Nginx service to apply changes
sudo service nginx restart
